location: 杭州

tmp_path: tmp

error_msg: 抱歉，出错了

asr:
    provider: azure
    azure:
        speech_key: aaaaa
        speech_region: japaneast
        language: zh-CN

keyword:
    provider: azure
    azure:
        # Refer to https://learn.microsoft.com/en-us/azure/ai-services/speech-service/custom-keyword-basics?pivots=programming-language-python
        model: assets/keyword_models/moss_cn.table # The path to the keyword model

tts:
    provider: edge-tts
    edge-tts:
        # Learn more about the Edge TTS at https://github.com/rany2/edge-tts
        voice_name: zh-CN-XiaoxiaoNeural # The voice name of the TTS, Use edge-tts --list-voices to get the list of voices

llm:
    provider: azure
    azure:
        api_key: 'aaaaa'
        endpoint: "https://aaaaa.openai.azure.com/"
        deployment: "gpt-35-turbo"
    openai: # Not Implemented Yet
        api_key: 'aaaaa'
        endpoint: "https://api.openai.com/v1/engines/gpt-3.5-turbo/completions"

agent_config:
    language: Chinese # Language of the Agent output
    openweathermap:
        enable: true
        api_key: 'aaaaa'
    google:
        enable: true
        cse_id: 'aaaaa'
        api_key: 'aaaaa'
    hass:
        enable: true
        host: "http://192.168.0.110" # Your Home Assistant url
        port: "8123" # Port of your Home Assistant
        # Use Your Home assistant long-lived access token to replace the token, keep the "Bearer" in front of the token
        key: "Bearer tokenstring"
        # The entity_id of the devices you want to control
        entity_ids:
            light.yeelink_bslamp2_1401_light: "卧室床头灯"
            script.pet_feeder_out: "宠物喂食器"
            climate.miir_ir02_5728_ir_aircondition_control: "卧室空调"